#+SETUPFILE: org-html-styles/readtheorg/theme-readtheorg-local.setup

#+TITLE: Форма отзыва научного руководителя по результатам педагогической практики
#+AUTHOR: Константин Моренко
#+EXPORT_FILE_NAME: index.md
#+LANGUAGE: ru

Отзыв научного руководителя по результатам практики предназначен для
оценки преподавателями проведенных аспирантами занятий.

* Введение
  :PROPERTIES:
  :CUSTOM_ID: intro
  :END:

Мне понадобилось составить отзыв о результатах педагогической
практики, и я столкнулся с совершенно чистым разлинованным листом
бумаги.  "О чем писать?" — подумал я.  После этого я составил форму
для отзыва.

Преимущества для преподавателей:
- ясные и однозначные критерии оценки аспирантов

Преимущества кафедры:
- наглядные и сопоставимые показатели обучения аспирантов
- статистический учет
- статистический профиль сильных/слабых мест в подготовке аспирантов

Недостатки:
- лень преподавателей писать, что может выразиться в том, что они
  будут "отписываться"

Эта форма отзыва охватывает *только одно занятие*.

* ChangeLog
  :PROPERTIES:
  :CUSTOM_ID: changelog
  :END:

** Доработать
   :PROPERTIES:
   :CUSTOM_ID: issues
   :END:

- [ ] Добавить пояснения о заполнении отзыва на оборотную сторону

** v. 1.0.0
   :PROPERTIES:
   :CUSTOM_ID: v1.0.0
   :END:

1. Ввел систему версий

   Не секрет, что электронные документы за время своей жизни
   претерпевают огромное количество изменений.  Например, мы захотим
   ввести новую форму отзыва, немного изменив всего один пункт.  Как
   проконтролировать, что все используют именно новую форму?
   Объяснять сущность изменений бывает трудно, а числа в номерах
   версий всегда просты и понятны.  Я использую [[https://semver.org][семантическое
   версионирование]].

2. Разделил отзыв на разделы

   Каждый из разделов: об аспиранте, о занятии, содержание отзыва и о
   руководителе содержит существенную информацию, но разделы не
   пересекаются между собой и не дублируют информацию.  Это позволяет
   избежать проблем несогласованности отдельных полей.

3. Добавил автоматические поля для записей от руки

   Единственный способ делать поля для записи от руки (подчеркивания),
   который я встречал, состоит в том, чтобы просто добавлять нужное
   количество знаков подчеркивания.  Такой подход неудобен тем, что
   при изменении в форме приходится либо добавлять новые либо удалять
   оставшиеся знаки подчеркивания, которые не доходят до конца
   строки.  Да и край строки остается неровным из-за неизменной ширины
   знака.
   
   Я включил в Абзаце Табуляцию и указал такие параметры: 17 см (это
   правый край страницы), по правому краю, заполнять "_".  С этими
   параметрами я просто ставлю знак табуляции там, где хочу сделать
   такое поле и вуаля — до конца строки прорисовывается четкая линия
   без разрывов.  Количество табуляций позволяет задать количество
   строк, которые мне нужно отвести под записи вручную.

4. Для всех пунктов где это возможно добавил пункты для выбора

   Пункты для выбора решают сразу две задачи: они позволяют
   сосредоточить внимание преподавателя, который заполняет форму, на
   ключевых аспектах того или иного вопроса.  При проведении
   статистического анализа эти пункты позволяют *сразу* получить
   необходимые карманы для сортировки результатов.  Разумеется, пункты
   вроде фамилии или даты выбором не представлены.

5. Пронумеровал пункты для выбора, чтобы их было легче адресовать

   Когда речь идет об обсуждении пунктов, то становится трудно
   перечислять их, поэтому ко всем пунктам я добавил номера.  Так
   проще: "во втором пункте выберите один и три".  При этом более
   высокие номера имеют пункты, отражающие более высокие показатели,
   например: 1 — плохой результат; 2 — средний результат; 3 — хороший
   результат.  Пункты с множественным выбором я пронумеровал буквами,
   потому что такие баллы в этом случае бесполезны.  Каждый буквенный
   пункт считается за один балл.
   
   В оценке проведенного занятия я изменил нумерацию пунктов так,
   чтобы она соответствовала неформальным названиям этих оценок:
   "отлично" — 5, "хорошо" — 4, "удовлетворительно" — 3,
   "неудовлетворительно" — 2.
   
   Обратите внимание, что при изменении номеров пунктов важно сделать
   так, чтобы числа не повторялись.  Если же нужно придать пунктам
   одинаковый вес, то можно добавить к цифре еще и букву: 3a, 3b, 3c.
   
   Если преподаватель предпочитает вписать свой пункт, то его нужно
   оценить в соответствии с баллами или буквой.  Для этого
   предусмотрены подсказки в виде скобок.

6. Всквозную пронумеровал все пункты формы

   По той же причине пронумеровал все пункты сквозной нумерацией.
   
7. Добавил электронный адрес расположения формы отзыва

   На каждой форме указан адрес, по которому можно найти не только
   саму форму, но и описание к ней и то, почему принята именно такая
   конструкция.

8. Ограничил форму одной страницей

   Если отзыв занимает больше одной страницы, то требуется как минимум
   нумерация страниц, а лучше система согласования страниц, чтобы их
   нельзя было перепутать, поскольку даже одному студенту придется
   иметь дело с несколькими отзывами.

*** Сумма баллов для оценки

Для оценки используются только пункты из разделов 3 и 4.  При этом в
разделе 3 сумма баллов может составлять 0–6; в разделе 4 сумма может
составлять 0–11 (4.1 — 0–3, 4.2 — 0–5).  Всего баллов может быть
0–17.

#+CAPTION: Оценки и соответствующие им баллы
| Оценка              | Диапазон  | Баллы             |
|---------------------+-----------+-------------------|
| неудовлетворительно | менее 55% | 9 и менее баллов  |
| удовлетворительно   | 55-75%    | 10–12 баллов      |
| хорошо              | 75-85%    | 13–14 баллов      |
| отлично             | более 85% | 15 и более баллов |

*** Маркировка пунктов

Я рассматриваю как результат только напечатанный бланк, хотя заполнить
его можно и на компьютере и на бумаге.  Варианты маркировки пунктов:

- компьютерная

  Пункты легко помечать с помощью выделения текста, которое при печати
  даже на черно-белом принтере будет давать серое поле под пунктом.
  
- бумажная (предпочтительно)

  На бумаге маркировать пункты лучше с помощью яркой ручки, например,
  синего или красного цвета или текстовыделителя.  При выделении с
  помощью ручки можно обводить цифры пункта вместе со скобками.  Для
  предотвращения махинаций с пунктами со множественным выбором те
  пункты, которые не были выполнены, можно зачеркивать.

* Файлы
  :PROPERTIES:
  :CUSTOM_ID: files
  :END:

- [[file:ped-practice-review.odt][odt]]
- [[file:ped-practice-review.docx][docx]]
- [[file:ped-practice-review.pdf][pdf]]
